
func fallback(d : int) -> int
{
    170 / d
}

func three(d : int, c : int) -> int
{
    170 / (d + c)
}

func two(d : int) -> int
{
    three(d, 0)
}
catch(division_by_zero)
{
    fallback(d)
}

func one(d : int) -> int
{
    two(d)
}
catch (division_by_zero)
{
    170
}

func main() -> int
{
    assert(one(0) == 170)
}


